### ISSUE TITLE
Smooch.login and okhttp , Crash NoClassDefFoundError Lokhttp3/internal/framed/Header 

### ISSUE THREAD

**Issue by Fraid** [smooch/smooch-android#125]
Hi guys,

Their is a conflict with the latest version of smooch `5.14.0` and okhttp `3.11.0`. 
App will crash with following error:
 
```
java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/framed/Header;
        at com.a.a.d.d(Unknown Source:28)
        at com.a.a.d.b(Unknown Source:0)
        at com.a.a.d$1.run(Unknown Source:434)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.framed.Header" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/.......etc
```

To reproduce the crash, with an empty project , call :
`Smooch.login(user_id, smooch_jwt,….);`
And add following in gradle file: 
```
      implementation 'com.squareup.okhttp3:okhttp:3.11.0'
      implementation 'io.smooch:core:5.14.0'
      implementation 'io.smooch:ui:5.14.0'
```

  ```
    compileSdkVersion = 27
    buildToolsVersion = "27.0.3"
    minSdkVersion = 21
    targetSdkVersion = 27
```

In following case, no crash will occurred and tchat history are available. 
-  smooch 5.13.3 and okhttp:3.11.0 
-  smooch 5.14.0 and okhttp:3.4.1 which is version a from 2 years ago .
I removed the app each time to be sure isn't cache issue.

Also if I used
```
    compileSdkVersion = 28
    buildToolsVersion = "28.0.2" 
    targetSdkVersion = 28
    implementation 'com.squareup.okhttp3:okhttp:3.11.0'
    implementation 'io.smooch:core:5.13.3'
    implementation 'io.smooch:ui:5.13.3'
```

App will crash with the following error
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/message/BasicLineParser;
        at com.a.a.d.c(Unknown Source:8)
        at com.a.a.d.a(Unknown Source:0)
        at com.a.a.d$1.run(Unknown Source:464)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicLineParser" on path: DexPathList[[zip file "/data/app/....etc
```

**Comment by wmora** [comment]
Thanks for the report, we'll look into it

**Comment by avinz** [comment]
Faced same issue after updating to 5.14.0

java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/framed/Header;
        at com.a.a.d.d(Unknown Source:51)
        at com.a.a.d.b(Unknown Source:0)
        at com.a.a.d$1.run(Unknown Source:480)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.framed.Header"

**Comment by wmora** [comment]
We identified the issue and will provide a new version with the fix tomorrow!

**Comment by wmora** [comment]
Fixed in version [5.14.1](https://github.com/smooch/smooch-android/releases/tag/5.14.1)
